### ISSUE TITLE
possible web service instability

### ISSUE THREAD

**Issue by rlcee** [fermitools/data_dispatcher#3]
issuing 
> ddisp project list

multiple times in a row, about 1 in 8 times, it will return a "not found" error (see attached).  This is true for other commands, like "ddisp worker next".

Following is the traceback

mu2ebuild01 rucio > ddisp project list
Traceback (most recent call last):
  File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/bin/ddisp", line 8, in <module>
    sys.exit(main())
  File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/ui/ui_main.py", line 198, in main
    cli.run(sys.argv, argv0="dd")
  File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 206, in run
    self._run(command, context, argv, usage_on_error)
  File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 201, in _run
    return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
  File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 201, in _run
    return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
  File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 100, in _run
    return self(command, context, opts, args)
  File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/ui/ui_project.py", line 335, in __call__
    lst = client.list_projects(state=state, attributes=attributes, owner=owner, with_files=True, with_replicas=False)
  File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/api.py", line 335, in list_projects
    return self.get(f"projects{args}")
  File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/metacat/common/http_client.py", line 165, in get
    return self.interpret_response(response, none_if_not_found)
  File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/metacat/common/http_client.py", line 145, in interpret_response
    raise NotFoundError(self.LastURL, response)
metacat.common.exceptions.NotFoundError

**Comment by marcmengel** [comment]
Restarted services on ifbcollector03.fnal.gov, which had been giving a 404 for the mu2e_dd_prod instance.

**Comment by marcmengel** [comment]
So to find this:
Ran "ddisp version" 25 times in a loop, got about 1/5 failures.
ssh  dbidata@dbdata2vm.fnal.gov
grep mu2e_dd_prod data_proxy/logs/requests.log  | grep -v 200

noted that all the failures were like:
  01/18/2024 20:21:27.826: [Service mu2e-dd-data]: BWU-374 bel-kwinith.fnal.gov(131.225.80.97):54838 -> :9443 [GET /mu2e_dd_prod/data/version HTTP/1.1] -> "mu2e-dd-data" ifbcollectorgpvm03.fnal.gov:9094 404 0 w:0.045 t:0.006

(that is they all went to ifbcollctorgpvm03.fnal.gov)

After touching the config.yaml for multiserver on that node, a batch of 25 ddisp version calls ran clean.
