### ISSUE TITLE
check project create return code

### ISSUE THREAD

**Issue by rlcee** [fermitools/data_dispatcher#6]
Called "ddisp project create" and got a web error (probably the intermittent error reported previously), but the strange thing is the command returned success, 0.  The last line in the attachment is output from "echo create $?" after the create command.

> Traceback (most recent call last):
>   File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/bin/ddisp", line 8, in <module>
>     sys.exit(main())
>   File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/ui/ui_main.py", line 198, in main
>     cli.run(sys.argv, argv0="dd")
>   File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 206, in run
>     self._run(command, context, argv, usage_on_error)
>   File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 201, in _run
>     return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
>   File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 201, in _run
>     return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
>   File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 100, in _run
>     return self(command, context, opts, args)
>   File "/cvmfs/mu2e.opensciencegrid.org/artexternals/datadispatcher/v01_26_00b/Linux64bit+3.10-2.17/lib/python3.9/site-packages/data_dispatcher/ui/ui_project.py", line 147, in __call__
>     print(info["project_id"])
> TypeError: 'NoneType' object is not subscriptable
> create 0:

**Comment by marcmengel** [comment]
``So, I'm trying to simulate the failiure we got when we got directed to a service node that wasn't configured right; by doing:
`DATA_DISPATCHER_URL=${DATA_DISPATCHER_URL}/wrong  ddisp project create "files from ..."`
This works in the sense that I get the same stack trace that @rlcee gets, above, but I do *not* get the zero exit code:
```
<bel-kwinith>$ DATA_DISPATCHER_URL=${DATA_DISPATCHER_URL}/wrong ddisp project create "files from mu2e:dts.mu2e.PiEPlusDecay.MDC2020t.art"
Traceback (most recent call last):
  File "/home/mengel/packages/data-dispatcher/1.26.0/linux-scientific7-x86_64_v2-gcc-4.8.5-4jp36gntb7dwxgoqlzhwq7lbh4xy45zu/bin/ddisp", line 8, in <module>
    sys.exit(main())
  File "/home/mengel/packages/data-dispatcher/1.26.0/linux-scientific7-x86_64_v2-gcc-4.8.5-4jp36gntb7dwxgoqlzhwq7lbh4xy45zu/lib/python3.9/site-packages/data_dispatcher/ui/ui_main.py", line 198, in main
    cli.run(sys.argv, argv0="dd")
  File "/home/mengel/packages/data-dispatcher/1.26.0/linux-scientific7-x86_64_v2-gcc-4.8.5-4jp36gntb7dwxgoqlzhwq7lbh4xy45zu/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 206, in run
    self._run(command, context, argv, usage_on_error)
  File "/home/mengel/packages/data-dispatcher/1.26.0/linux-scientific7-x86_64_v2-gcc-4.8.5-4jp36gntb7dwxgoqlzhwq7lbh4xy45zu/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 201, in _run
    return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
  File "/home/mengel/packages/data-dispatcher/1.26.0/linux-scientific7-x86_64_v2-gcc-4.8.5-4jp36gntb7dwxgoqlzhwq7lbh4xy45zu/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 201, in _run
    return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
  File "/home/mengel/packages/data-dispatcher/1.26.0/linux-scientific7-x86_64_v2-gcc-4.8.5-4jp36gntb7dwxgoqlzhwq7lbh4xy45zu/lib/python3.9/site-packages/data_dispatcher/ui/cli/cli.py", line 100, in _run
    return self(command, context, opts, args)
  File "/home/mengel/packages/data-dispatcher/1.26.0/linux-scientific7-x86_64_v2-gcc-4.8.5-4jp36gntb7dwxgoqlzhwq7lbh4xy45zu/lib/python3.9/site-packages/data_dispatcher/ui/ui_project.py", line 147, in __call__
    print(info["project_id"])
TypeError: 'NoneType' object is not subscriptable

<bel-kwinith>$ echo $?
1
```
This is with:
```
<bel-kwinith>$ ddisp version
Server URL:     https://metacat.fnal.gov:9443/mu2e_dd_prod/data
Server version: 1.26.4
Client version: 1.26.0
```
Although for this purpose I think only the client version matters... @rlcee , can you tell me which version of the data_dispatcher client you're using?

**Comment by rlcee** [comment]
```
Server URL:     https://metacat.fnal.gov:9443/mu2e_dd_prod/data
Server version: 1.26.4
Client version: 1.26.0
```
OK, thanks, I will keep an eye out, but we can put this one on hold

**Comment by marcmengel** [comment]
@rlcee, have you had any more instances of this?  If not I think we should close it out.

**Comment by rlcee** [comment]
I don't think I've seen this since this one instance, but it would only happen with the service error, which is rare.    I don't expect to be creating projects at scale, so I am OK closing this..  I'll let you know if I see it again.
